/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WebpayImport } from './routes/webpay'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as PaymentOrderIdImport } from './routes/payment/$orderId'

// Create/Update Routes

const WebpayRoute = WebpayImport.update({
  id: '/webpay',
  path: '/webpay',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PaymentOrderIdRoute = PaymentOrderIdImport.update({
  id: '/payment/$orderId',
  path: '/payment/$orderId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/webpay': {
      id: '/webpay'
      path: '/webpay'
      fullPath: '/webpay'
      preLoaderRoute: typeof WebpayImport
      parentRoute: typeof rootRoute
    }
    '/payment/$orderId': {
      id: '/payment/$orderId'
      path: '/payment/$orderId'
      fullPath: '/payment/$orderId'
      preLoaderRoute: typeof PaymentOrderIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/webpay': typeof WebpayRoute
  '/payment/$orderId': typeof PaymentOrderIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/webpay': typeof WebpayRoute
  '/payment/$orderId': typeof PaymentOrderIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/webpay': typeof WebpayRoute
  '/payment/$orderId': typeof PaymentOrderIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/webpay' | '/payment/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/webpay' | '/payment/$orderId'
  id: '__root__' | '/' | '/about' | '/webpay' | '/payment/$orderId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  WebpayRoute: typeof WebpayRoute
  PaymentOrderIdRoute: typeof PaymentOrderIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  WebpayRoute: WebpayRoute,
  PaymentOrderIdRoute: PaymentOrderIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/webpay",
        "/payment/$orderId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/webpay": {
      "filePath": "webpay.tsx"
    },
    "/payment/$orderId": {
      "filePath": "payment/$orderId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
