/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WalletScanRouteImport } from './routes/wallet/scan'
import { Route as WalletPayRouteImport } from './routes/wallet/pay'
import { Route as WebpayOrder_idOrderIdRouteImport } from './routes/webpay/order_id/$orderId'
import { Route as WalletPayPaynowRouteImport } from './routes/wallet/pay/paynow'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletScanRoute = WalletScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => WalletRoute,
} as any)
const WalletPayRoute = WalletPayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => WalletRoute,
} as any)
const WebpayOrder_idOrderIdRoute = WebpayOrder_idOrderIdRouteImport.update({
  id: '/webpay/order_id/$orderId',
  path: '/webpay/order_id/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletPayPaynowRoute = WalletPayPaynowRouteImport.update({
  id: '/paynow',
  path: '/paynow',
  getParentRoute: () => WalletPayRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/wallet': typeof WalletRouteWithChildren
  '/wallet/pay': typeof WalletPayRouteWithChildren
  '/wallet/scan': typeof WalletScanRoute
  '/wallet/pay/paynow': typeof WalletPayPaynowRoute
  '/webpay/order_id/$orderId': typeof WebpayOrder_idOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/wallet': typeof WalletRouteWithChildren
  '/wallet/pay': typeof WalletPayRouteWithChildren
  '/wallet/scan': typeof WalletScanRoute
  '/wallet/pay/paynow': typeof WalletPayPaynowRoute
  '/webpay/order_id/$orderId': typeof WebpayOrder_idOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/wallet': typeof WalletRouteWithChildren
  '/wallet/pay': typeof WalletPayRouteWithChildren
  '/wallet/scan': typeof WalletScanRoute
  '/wallet/pay/paynow': typeof WalletPayPaynowRoute
  '/webpay/order_id/$orderId': typeof WebpayOrder_idOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/wallet'
    | '/wallet/pay'
    | '/wallet/scan'
    | '/wallet/pay/paynow'
    | '/webpay/order_id/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/wallet'
    | '/wallet/pay'
    | '/wallet/scan'
    | '/wallet/pay/paynow'
    | '/webpay/order_id/$orderId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/login'
    | '/wallet'
    | '/wallet/pay'
    | '/wallet/scan'
    | '/wallet/pay/paynow'
    | '/webpay/order_id/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  WalletRoute: typeof WalletRouteWithChildren
  WebpayOrder_idOrderIdRoute: typeof WebpayOrder_idOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/scan': {
      id: '/wallet/scan'
      path: '/scan'
      fullPath: '/wallet/scan'
      preLoaderRoute: typeof WalletScanRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/pay': {
      id: '/wallet/pay'
      path: '/pay'
      fullPath: '/wallet/pay'
      preLoaderRoute: typeof WalletPayRouteImport
      parentRoute: typeof WalletRoute
    }
    '/webpay/order_id/$orderId': {
      id: '/webpay/order_id/$orderId'
      path: '/webpay/order_id/$orderId'
      fullPath: '/webpay/order_id/$orderId'
      preLoaderRoute: typeof WebpayOrder_idOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/pay/paynow': {
      id: '/wallet/pay/paynow'
      path: '/paynow'
      fullPath: '/wallet/pay/paynow'
      preLoaderRoute: typeof WalletPayPaynowRouteImport
      parentRoute: typeof WalletPayRoute
    }
  }
}

interface WalletPayRouteChildren {
  WalletPayPaynowRoute: typeof WalletPayPaynowRoute
}

const WalletPayRouteChildren: WalletPayRouteChildren = {
  WalletPayPaynowRoute: WalletPayPaynowRoute,
}

const WalletPayRouteWithChildren = WalletPayRoute._addFileChildren(
  WalletPayRouteChildren,
)

interface WalletRouteChildren {
  WalletPayRoute: typeof WalletPayRouteWithChildren
  WalletScanRoute: typeof WalletScanRoute
}

const WalletRouteChildren: WalletRouteChildren = {
  WalletPayRoute: WalletPayRouteWithChildren,
  WalletScanRoute: WalletScanRoute,
}

const WalletRouteWithChildren =
  WalletRoute._addFileChildren(WalletRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  WalletRoute: WalletRouteWithChildren,
  WebpayOrder_idOrderIdRoute: WebpayOrder_idOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
